bootCore()

test("filters are per character by default", function()
    QuestPrism.Settings.Set("Campaign", false)
    assertEq(QuestPrismCharDB.Campaign, false)
    assertEq(QuestPrism.Settings.IsAccountWide(), false)
end)

test("enabling account-wide seeds the account table from this character", function()
    QuestPrismCharDB.Campaign = false
    QuestPrismCharDB.HideWorldQuests = true
    QuestPrism.Settings.SetAccountWide(true)
    assertEq(QuestPrism.Settings.IsAccountWide(), true)
    assertEq(QuestPrismDB.filters.Campaign, false, "seeded Campaign")
    assertEq(QuestPrismDB.filters.HideWorldQuests, true, "seeded world quest block")
    QuestPrism.Settings.Set("HideWorldQuests", false)
    assertEq(QuestPrism.Settings.Get("Campaign"), false)
end)

test("account-wide reads and writes go to the account table", function()
    QuestPrism.Settings.SetAccountWide(true)
    QuestPrism.Settings.Set("Legendary", false)
    assertEq(QuestPrismDB.filters.Legendary, false)
    assertEq(QuestPrismCharDB.Legendary, true, "character value untouched")
    assertEq(QuestPrism.Settings.Get("Legendary"), false)
end)

test("non-filter keys stay per character even when account-wide", function()
    QuestPrism.Settings.SetAccountWide(true)
    QuestPrism.Settings.Set("debug", true)
    assertEq(QuestPrismCharDB.debug, true)
    assertEq(QuestPrismDB.filters.debug, nil)
    QuestPrism.Settings.Set("debug", false)
end)

test("disabling account-wide falls back to character values", function()
    QuestPrism.Settings.SetAccountWide(true)
    QuestPrism.Settings.Set("Meta", false)
    QuestPrism.Settings.SetAccountWide(false)
    assertEq(QuestPrism.Settings.Get("Meta"), true)
end)

test("presets and Reset honor the active scope", function()
    QuestPrism.Settings.SetAccountWide(true)
    QuestPrism.Settings.Set("Important", false)
    QuestPrism.Settings.SavePreset("acct")
    assertEq(QuestPrismDB.presets.acct.Important, false)
    QuestPrism.Settings.Reset()
    assertEq(QuestPrismDB.filters.Important, true)
    QuestPrism.Settings.LoadPreset("acct")
    assertEq(QuestPrism.Settings.Get("Important"), false)
end)

test("Trivial is a scoped filter key defaulting to hidden", function()
    QuestPrismCharDB = nil; QuestPrismDB = nil; QuestPrism.Settings.Initialize()
    assertEq(QuestPrism.Settings.Get("Trivial"), false)
    QuestPrism.Settings.SetAccountWide(true)
    QuestPrism.Settings.Set("Trivial", true)
    assertEq(QuestPrismDB.filters.Trivial, true)
    QuestPrism.Settings.SetAccountWide(false)
end)

test("Reset shows trivial quests too, and dimFiltered defaults off", function()
    QuestPrism.Settings.Set("Trivial", false)
    QuestPrism.Settings.Reset()
    assertEq(QuestPrism.Settings.Get("Trivial"), true)
    assertEq(QuestPrism.Settings.Get("dimFiltered"), false)
end)

test("HideWorldQuests defaults off, is saved in presets, and Reset lifts it", function()
    assertEq(QuestPrism.Settings.Get("HideWorldQuests"), false)
    QuestPrism.Settings.Set("HideWorldQuests", true)
    QuestPrism.Settings.SavePreset("Blocked")
    assertEq(QuestPrismDB.presets.Blocked.HideWorldQuests, true, "in the preset")
    QuestPrism.Settings.Reset()
    assertEq(QuestPrism.Settings.Get("HideWorldQuests"), false, "Show all lifts the block")
    QuestPrism.Settings.LoadPreset("Blocked")
    assertEq(QuestPrism.Settings.Get("HideWorldQuests"), true, "restored by the preset")
    QuestPrism.Settings.Set("HideWorldQuests", false)
    QuestPrism.Settings.DeletePreset("Blocked")
end)

test("Initialize drops the retired HideWarbandCompleted keys from every store", function()
    QuestPrismCharDB = { HideWarbandCompleted_Meta = true, Campaign = false }
    QuestPrismDB = { filters = { HideWarbandCompleted_Campaign = false }, presets = { Old = { Meta = true, HideWarbandCompleted_Meta = true } } }
    QuestPrism.Settings.Initialize()
    assertEq(QuestPrismCharDB.HideWarbandCompleted_Meta, nil, "char store")
    assertEq(QuestPrismCharDB.Campaign, false, "other keys untouched")
    assertEq(QuestPrismDB.filters.HideWarbandCompleted_Campaign, nil, "account store")
    assertEq(QuestPrismDB.presets.Old.HideWarbandCompleted_Meta, nil, "preset")
    assertEq(QuestPrismDB.presets.Old.Meta, true, "preset keeps its toggles")
    QuestPrismDB.presets = nil
end)

test("Solo shows only one type and a second Solo restores the previous filters", function()
    QuestPrism.Settings.Reset()
    QuestPrism.Settings.Set("Meta", false); QuestPrism.Settings.Set("Trivial", false)
    QuestPrism.Settings.Solo("Campaign")
    assertTrue(QuestPrism.Settings.IsSoloed("Campaign"))
    assertEq(QuestPrism.Settings.Get("Campaign"), true)
    for _, k in ipairs({ "Important", "Legendary", "Meta", "Repeatable", "LocalStory", "Expedition", "Trivial" }) do
        assertEq(QuestPrism.Settings.Get(k), false, k .. " should be hidden while soloed")
    end
    assertEq(QuestPrism.Settings.Get("HideWorldQuests"), true, "world quests hidden while soloed")
    QuestPrism.Settings.Solo("Campaign")
    assertFalse(QuestPrism.Settings.IsSoloed("Campaign"))
    assertEq(QuestPrism.Settings.Get("Meta"), false, "restored Meta")
    assertEq(QuestPrism.Settings.Get("Important"), true, "restored Important")
    assertEq(QuestPrism.Settings.Get("Trivial"), false, "restored Trivial")
    assertEq(QuestPrism.Settings.Get("HideWorldQuests"), false, "restored world quests")
end)

test("HideAll clears every row including World Quests; Reset brings them all back", function()
    QuestPrism.Settings.Reset()
    QuestPrism.Settings.HideAll()
    for _, k in ipairs({ "Campaign", "Important", "Legendary", "Meta", "Repeatable", "LocalStory", "Expedition", "Trivial" }) do
        assertEq(QuestPrism.Settings.Get(k), false, k)
    end
    assertEq(QuestPrism.Settings.Get("HideWorldQuests"), true, "world quests hidden too")
    QuestPrism.Settings.Reset()
    assertEq(QuestPrism.Settings.Get("HideWorldQuests"), false)
end)

test("Initialize renames saved presets that share a built-in's name", function()
    QuestPrismCharDB = { activePreset = "endgame" }
    QuestPrismDB = { presets = { endgame = { Campaign = false }, Mine = { Meta = false }, ["Leveling (yours)"] = { Meta = true }, Leveling = { Meta = false } } }
    QuestPrism.Settings.Initialize()
    assertEq(QuestPrismDB.presets.endgame, nil, "shadowed name gone")
    assertEq(QuestPrismDB.presets["endgame (yours)"].Campaign, false, "kept under the new name")
    assertEq(QuestPrismDB.presets.Mine.Meta, false, "others untouched")
    assertEq(QuestPrismDB.presets.Leveling, nil)
    assertEq(QuestPrismDB.presets["Leveling (yours) (yours)"].Meta, false, "suffix repeated when taken")
    assertEq(QuestPrismCharDB.activePreset, "endgame (yours)", "active preset follows the rename")
    assertEq(QuestPrism.Settings.GetActivePresetName(), "endgame (yours)")
    QuestPrismDB.presets = nil
end)

test("Solo on a different type while soloed switches without losing the snapshot", function()
    QuestPrism.Settings.Reset(); QuestPrism.Settings.Set("Meta", false)
    QuestPrism.Settings.Solo("Campaign"); QuestPrism.Settings.Solo("Legendary")
    assertTrue(QuestPrism.Settings.IsSoloed("Legendary")); assertEq(QuestPrism.Settings.Get("Campaign"), false)
    QuestPrism.Settings.Solo("Legendary")
    assertEq(QuestPrism.Settings.Get("Meta"), false, "snapshot kept"); assertEq(QuestPrism.Settings.Get("Campaign"), true)
end)

test("a manual change while soloed ends solo mode without restoring", function()
    QuestPrism.Settings.Reset()
    QuestPrism.Settings.Solo("Campaign")
    QuestPrism.Settings.Set("Meta", true)
    assertFalse(QuestPrism.Settings.IsSoloed("Campaign"))
    assertEq(QuestPrism.Settings.Get("Important"), false, "no restore on manual change")
    QuestPrism.Settings.Reset()
end)

-- Built-in presets (read-only, listed before saved ones)
test("built-in presets are listed in a fixed order and recognised by name", function()
    local names = QuestPrism.Settings.ListBuiltInPresetNames()
    assertEq(#names, 4)
    assertEq(names[1], "Leveling"); assertEq(names[2], "Campaign only")
    assertEq(names[3], "Endgame"); assertEq(names[4], "Weekly chores")
    assertTrue(QuestPrism.Settings.IsBuiltInPreset("Leveling"))
    assertFalse(QuestPrism.Settings.IsBuiltInPreset("Mine"))
end)

test("loading a built-in preset applies its rows and becomes the active preset", function()
    QuestPrism.Settings.SetAccountWide(false)
    QuestPrism.Settings.Reset()
    QuestPrism.Settings.LoadPreset("Leveling")
    assertEq(QuestPrism.Settings.Get("Campaign"), true); assertEq(QuestPrism.Settings.Get("Important"), true)
    assertEq(QuestPrism.Settings.Get("LocalStory"), true)
    assertEq(QuestPrism.Settings.Get("Legendary"), false); assertEq(QuestPrism.Settings.Get("Meta"), false)
    assertEq(QuestPrism.Settings.Get("Repeatable"), false); assertEq(QuestPrism.Settings.Get("Expedition"), false)
    assertEq(QuestPrism.Settings.Get("Trivial"), false)
    assertEq(QuestPrism.Settings.Get("HideWorldQuests"), true, "world quests blocked by Leveling")
    assertEq(QuestPrism.Settings.GetActivePresetName(), "Leveling")
    QuestPrism.Settings.LoadPreset("Weekly chores")
    assertEq(QuestPrism.Settings.Get("Campaign"), false); assertEq(QuestPrism.Settings.Get("Meta"), true)
    assertEq(QuestPrism.Settings.Get("Repeatable"), true); assertEq(QuestPrism.Settings.Get("Expedition"), true)
    assertEq(QuestPrism.Settings.Get("HideWorldQuests"), false, "world quests shown by Weekly chores")
    QuestPrism.Settings.LoadPreset("Endgame")
    assertEq(QuestPrism.Settings.Get("LocalStory"), false); assertEq(QuestPrism.Settings.Get("Legendary"), true)
    assertEq(QuestPrism.Settings.Get("HideWorldQuests"), false)
    QuestPrism.Settings.LoadPreset("Campaign only")
    assertEq(QuestPrism.Settings.Get("Legendary"), true); assertEq(QuestPrism.Settings.Get("LocalStory"), false)
    assertEq(QuestPrism.Settings.Get("HideWorldQuests"), true)
    local snapshot = QuestPrism.Settings.GetPresetSnapshot("Leveling")
    assertEq(snapshot.Campaign, true); assertEq(snapshot.HideWorldQuests, true)
    assertEq(QuestPrism.Settings.GetPresetSnapshot("Nope"), nil)
end)

test("built-in presets cannot be overwritten or deleted", function()
    assertFalse(QuestPrism.Settings.SavePreset("Leveling"), "save refused")
    assertFalse(QuestPrism.Settings.SavePreset("leveling"), "save refused, case-insensitive")
    assertEq(QuestPrismDB.presets and QuestPrismDB.presets.Leveling, nil, "nothing stored")
    QuestPrism.Settings.DeletePreset("Leveling")
    assertTrue(QuestPrism.Settings.IsBuiltInPreset("Leveling"), "still there")
    assertTrue(QuestPrism.Settings.SavePreset("Mine"), "saving a normal name works")
    assertEq(QuestPrism.Settings.GetActivePresetName(), "Mine", "saving selects the preset")
    QuestPrism.Settings.DeletePreset("Mine")
    assertEq(QuestPrism.Settings.GetActivePresetName(), nil, "deleting the active preset clears it")
end)

test("editing a row keeps the active preset and flags it as modified", function()
    QuestPrism.Settings.LoadPreset("Leveling")
    assertFalse(QuestPrism.Settings.IsActivePresetModified())
    QuestPrism.Settings.Set("Meta", true)
    assertEq(QuestPrism.Settings.GetActivePresetName(), "Leveling", "still the active preset")
    assertTrue(QuestPrism.Settings.IsActivePresetModified())
    QuestPrism.Settings.Set("Meta", false)
    assertFalse(QuestPrism.Settings.IsActivePresetModified(), "back to the preset")
    QuestPrism.Settings.Set("HideWorldQuests", false)
    assertTrue(QuestPrism.Settings.IsActivePresetModified(), "the world quest row counts")
    QuestPrism.Settings.Reset()
    assertFalse(QuestPrism.Settings.IsActivePresetModified(), "no active preset, never modified")
end)

test("saved presets missing a newer key compare against the default", function()
    QuestPrismDB.presets = { Old = { Campaign = false } }
    QuestPrism.Settings.LoadPreset("Old")
    assertFalse(QuestPrism.Settings.IsActivePresetModified())
    QuestPrismDB.presets = nil
end)

test("Initialize drops the stale collapsed-sections table", function()
    QuestPrismCharDB = { collapsed = { guide = true } }
    QuestPrism.Settings.Initialize()
    assertEq(QuestPrismCharDB.collapsed, nil)
    assertEq(QuestPrism.Settings.IsCollapsed, nil, "collapse API removed")
end)

test("Initialize drops the retired first-run popup marker", function()
    QuestPrismCharDB = {}; QuestPrismDB = { lastSeenVersion = "1.0.0-beta2" }
    QuestPrism.Settings.Initialize()
    assertEq(QuestPrismDB.lastSeenVersion, nil)
end)
